# on: 
#     push:
#         branches:
#             - main
# name: ðŸš€ Deploy website on push
# jobs:
#   web-deploy:
#     name: ðŸŽ‰ Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: ðŸšš Get latest code
#       uses: actions/checkout@v3
#     # - name: Install dependencies
#     #   run: npm install
#     # - name: Build TypeScript
#     #   run: npm run build

#     - name: ðŸ“‚ Sync files
#       uses: pressidium/lftp-mirror-action@v1
#       with:
#         host: ${{ secrets.ftps_host }}
#         user: ${{ secrets.ftps_user }}
#         pass: ${{ secrets.ftps_password }}
#         localDir: '.'
#         remoteDir: '/var/www/html/example.com/public'
#         # server-dir: portifolio-react/
#         port: 22 # todo replace with your web hosts ftps port
#         # timeout: 120000 